/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author alons
 */
public class VProveedores extends javax.swing.JInternalFrame {

    /**
     * Creates new form VProveedores
     */
    public VProveedores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtRucprov = new javax.swing.JTextField();
        txtNombreprov = new javax.swing.JTextField();
        txtTelefonoprov = new javax.swing.JTextField();
        txtDireccionprov = new javax.swing.JTextField();
        jbtnRegistrarprov = new javax.swing.JButton();
        jbtnConsultarprov = new javax.swing.JButton();
        jbtnActualizarprov = new javax.swing.JButton();
        jbtnEliminarprov = new javax.swing.JButton();
        txtIdproveedor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        txtCodigoprov = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblDatosprov = new javax.swing.JTable();
        jlblRegistrosprov = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(33, 45, 62));
        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(33, 45, 62));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registro de Proveedores");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("RUC");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NOMBRE");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TELEFONO");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DIRECCION");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        txtRucprov.setBackground(new java.awt.Color(33, 45, 62));
        txtRucprov.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtRucprov.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtRucprov, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 150, 30));

        txtNombreprov.setBackground(new java.awt.Color(33, 45, 62));
        txtNombreprov.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtNombreprov.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreprov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreprovActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombreprov, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 150, 30));

        txtTelefonoprov.setBackground(new java.awt.Color(33, 45, 62));
        txtTelefonoprov.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtTelefonoprov.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtTelefonoprov, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 150, 30));

        txtDireccionprov.setBackground(new java.awt.Color(33, 45, 62));
        txtDireccionprov.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtDireccionprov.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtDireccionprov, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 150, 30));

        jbtnRegistrarprov.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnRegistrarprov.setText("REGISTRAR");
        jPanel1.add(jbtnRegistrarprov, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 111, 33));

        jbtnConsultarprov.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnConsultarprov.setText("CONSULTAR");
        jPanel1.add(jbtnConsultarprov, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, -1, 33));

        jbtnActualizarprov.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnActualizarprov.setText("ACTUALIZAR");
        jPanel1.add(jbtnActualizarprov, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, -1, 34));

        jbtnEliminarprov.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnEliminarprov.setText("ELIMINAR");
        jPanel1.add(jbtnEliminarprov, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 490, 110, 34));

        txtIdproveedor.setEditable(false);
        txtIdproveedor.setBackground(new java.awt.Color(33, 45, 62));
        txtIdproveedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtIdproveedor.setForeground(new java.awt.Color(255, 255, 255));
        txtIdproveedor.setBorder(null);
        txtIdproveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdproveedorActionPerformed(evt);
            }
        });
        jPanel1.add(txtIdproveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 41, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\alons\\OneDrive\\Documentos\\NetBeansProjects\\ProyectoFinal\\src\\Imagenes\\icons8_supplier_50px.png")); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 60, 50));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 60, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 170, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 170, -1));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 170, -1));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 170, -1));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 170, 10));

        txtCodigoprov.setBackground(new java.awt.Color(33, 45, 62));
        txtCodigoprov.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtCodigoprov.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtCodigoprov, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 150, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("CODIGO");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 360, 540));

        jtblDatosprov.setBackground(new java.awt.Color(73, 181, 172));
        jtblDatosprov.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jtblDatosprov.setForeground(new java.awt.Color(255, 255, 255));
        jtblDatosprov.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane1.setViewportView(jtblDatosprov);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 590, 530));

        jlblRegistrosprov.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblRegistrosprov.setForeground(new java.awt.Color(255, 255, 255));
        jlblRegistrosprov.setText("NUMERO DE PROVEEDORES REGISTRADOS:");
        getContentPane().add(jlblRegistrosprov, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 600, 500, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\alons\\OneDrive\\Documentos\\NetBeansProjects\\ProyectoFinal\\src\\Imagenes\\icons8_people_50px.png")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 600, 50, 40));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 640, 600, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreprovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreprovActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreprovActionPerformed

    private void txtIdproveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdproveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdproveedorActionPerformed

    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VProveedores().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    public javax.swing.JButton jbtnActualizarprov;
    public javax.swing.JButton jbtnConsultarprov;
    public javax.swing.JButton jbtnEliminarprov;
    public javax.swing.JButton jbtnRegistrarprov;
    public javax.swing.JLabel jlblRegistrosprov;
    public javax.swing.JTable jtblDatosprov;
    public javax.swing.JTextField txtCodigoprov;
    public javax.swing.JTextField txtDireccionprov;
    public javax.swing.JTextField txtIdproveedor;
    public javax.swing.JTextField txtNombreprov;
    public javax.swing.JTextField txtRucprov;
    public javax.swing.JTextField txtTelefonoprov;
    // End of variables declaration//GEN-END:variables
}
