/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author alons
 */
public class VUsuarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form VUsuarios
     */
    public VUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombreusuario = new javax.swing.JTextField();
        txtCodigousuario = new javax.swing.JTextField();
        txtCorreousuario = new javax.swing.JTextField();
        txtContraseñausuario = new javax.swing.JTextField();
        txtIdusuario = new javax.swing.JTextField();
        btnRegistrarusuario = new javax.swing.JButton();
        btnConsultarusuario = new javax.swing.JButton();
        btnActualizarusuario = new javax.swing.JButton();
        btnEliminarusuario = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblDatosusuario = new javax.swing.JTable();
        jlblRegistrosusuarios = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(33, 45, 62));
        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(33, 45, 62));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REGISTRO DE USUARIOS ADM");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 300, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombres");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Codigo");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Correo");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Contraseña");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        txtNombreusuario.setBackground(new java.awt.Color(33, 45, 62));
        txtNombreusuario.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtNombreusuario.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreusuarioActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombreusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 150, 30));

        txtCodigousuario.setBackground(new java.awt.Color(33, 45, 62));
        txtCodigousuario.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtCodigousuario.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtCodigousuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 150, 30));

        txtCorreousuario.setBackground(new java.awt.Color(33, 45, 62));
        txtCorreousuario.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtCorreousuario.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtCorreousuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 150, 30));

        txtContraseñausuario.setBackground(new java.awt.Color(33, 45, 62));
        txtContraseñausuario.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtContraseñausuario.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtContraseñausuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 150, 30));

        txtIdusuario.setEditable(false);
        txtIdusuario.setBackground(new java.awt.Color(33, 45, 62));
        txtIdusuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtIdusuario.setForeground(new java.awt.Color(255, 255, 255));
        txtIdusuario.setBorder(null);
        txtIdusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdusuarioActionPerformed(evt);
            }
        });
        jPanel1.add(txtIdusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 30, 30));

        btnRegistrarusuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRegistrarusuario.setText("Registrar");
        btnRegistrarusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarusuarioActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 110, 30));

        btnConsultarusuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnConsultarusuario.setText("Consultar");
        jPanel1.add(btnConsultarusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 110, 30));

        btnActualizarusuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnActualizarusuario.setText("Actualizar");
        jPanel1.add(btnActualizarusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 110, 30));

        btnEliminarusuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEliminarusuario.setText("Eliminar");
        jPanel1.add(btnEliminarusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 110, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\alons\\OneDrive\\Documentos\\NetBeansProjects\\ProyectoFinal\\src\\Imagenes\\icons8_sql_database_administrators_group_50px.png")); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 60, 60));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\alons\\OneDrive\\Documentos\\NetBeansProjects\\ProyectoFinal\\src\\Imagenes\\icons8_command_line_30px.png")); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 30, 40));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 170, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 170, -1));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, -1));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 170, -1));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 170, -1));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 93, 66, 9));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 340, 480));

        jtblDatosusuario.setBackground(new java.awt.Color(73, 181, 172));
        jtblDatosusuario.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jtblDatosusuario.setForeground(new java.awt.Color(255, 255, 255));
        jtblDatosusuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(jtblDatosusuario);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 610, 480));

        jlblRegistrosusuarios.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblRegistrosusuarios.setForeground(new java.awt.Color(255, 255, 255));
        jlblRegistrosusuarios.setText("NUMERO DE USUARIOS REGISTRADOS EN LA EMPRESA:");
        getContentPane().add(jlblRegistrosusuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 590, 620, 40));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 610, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 630, 630, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\alons\\OneDrive\\Documentos\\NetBeansProjects\\ProyectoFinal\\src\\Imagenes\\icons8_people_50px.png")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 590, 50, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarusuarioActionPerformed

    private void txtNombreusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreusuarioActionPerformed

    private void txtIdusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdusuarioActionPerformed
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VUsuarios().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizarusuario;
    public javax.swing.JButton btnConsultarusuario;
    public javax.swing.JButton btnEliminarusuario;
    public javax.swing.JButton btnRegistrarusuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    public javax.swing.JLabel jlblRegistrosusuarios;
    public javax.swing.JTable jtblDatosusuario;
    public javax.swing.JTextField txtCodigousuario;
    public javax.swing.JTextField txtContraseñausuario;
    public javax.swing.JTextField txtCorreousuario;
    public javax.swing.JTextField txtIdusuario;
    public javax.swing.JTextField txtNombreusuario;
    // End of variables declaration//GEN-END:variables
}
